version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    volumes: 
      - "/var/lib/mysql/data:${MARIADB_DATA_DIR}"
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: Books
    ports:
        - "${PORT}:3306"

